
server:
  port: 8080

logging:
  level:
    root: INFO
    com:
      scurtis:
        nflstats: TRACE

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: scurtis






